package com.api.tests.products;

import com.api.config.ApiConfig;
import com.api.base.TestBase;
import io.qameta.allure.*;
import io.restassured.module.jsv.JsonSchemaValidator;
import io.restassured.response.Response;
import org.junit.jupiter.api.*;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;

import java.util.Map;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;
import static org.junit.jupiter.api.Assertions.*;

@Epic("API Test Automation")
@Feature("Product Management")
@Story("CREATE Products")
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
@DisplayName("POST Create API Tests")
public class CreateProductTests extends TestBase {

    @ParameterizedTest(name = "POST /products — valid payload {0}")
    @Order(1)
    @AllureId("P-001")
    @MethodSource("com.api.tests.products.ProductDataFactory#validProductProvider")
    @Severity(SeverityLevel.BLOCKER)
    @Description("API: POST /products. Validates that various valid payloads return success.")
    void testCreateProduct_WithValidPayload_ShouldReturnSuccess(Map<String, Object> payload) {
        given()
                .spec(requestSpec)
                .body(payload)
                .when()
                .post(ApiConfig.PRODUCTS_ENDPOINT)
                .then()
                .statusCode(anyOf(equalTo(200), equalTo(201)))
                .body("id", notNullValue())
                .body("title", equalTo(payload.get("title")))
                .body("description", equalTo(payload.get("description")));
    }

    @Test
    @Order(2)
    @AllureId("P-002")
    @DisplayName("POST /products — created product should have an auto-generated ID")
    @Severity(SeverityLevel.CRITICAL)
    @Description("API: POST /products. Checks that the created product has an auto-generated ID.")
    void testCreateProduct_ShouldReturnAutoGeneratedId() {
        Response response = given()
                .spec(requestSpec)
                .body(ProductDataFactory.createValidProduct())
                .when()
                .post(ApiConfig.PRODUCTS_ENDPOINT)
                .then()
                .statusCode(anyOf(equalTo(200), equalTo(201)))
                .extract().response();

        Integer generatedId = response.jsonPath().get("id");
        assertNotNull(generatedId, "Generated ID must not be null");
        log.info("Created product with ID: {}", generatedId);
    }

    @Test
    @Order(3)
    @AllureId("P-003")
    @DisplayName("POST /products — response body should fully match the request")
    @Severity(SeverityLevel.CRITICAL)
    @Description("API: POST /products. Ensures the response body matches the request payload.")
    void testCreateProduct_ResponseBodyShouldMatchRequest() {
        String expectedTitle = "Test Title " + System.currentTimeMillis();
        String expectedDescription = "Test description content.";
        double expectedPrice = 20.5;

        java.util.Map<String, Object> payload = new java.util.HashMap<>();
        payload.put("title", expectedTitle);
        payload.put("price", expectedPrice);
        payload.put("description", expectedDescription);

        given()
                .spec(requestSpec)
                .body(payload)
                .when()
                .post(ApiConfig.PRODUCTS_ENDPOINT)
                .then()
                .statusCode(anyOf(equalTo(200), equalTo(201)))
                .body("title", equalTo(expectedTitle))
                .body("description", equalTo(expectedDescription));
    }

    @Test
    @Order(4)
    @AllureId("P-004")
    @DisplayName("POST /products — response should match product JSON schema")
    @Severity(SeverityLevel.CRITICAL)
    @Description("API: POST /products. Validates that the created product response matches the expected JSON schema.")
    void testCreateProduct_ShouldMatchProductJsonSchema() {
        given()
                .spec(requestSpec)
                .body(ProductDataFactory.createValidProduct())
                .when()
                .post(ApiConfig.PRODUCTS_ENDPOINT)
                .then()
                .statusCode(anyOf(equalTo(200), equalTo(201)))
                .body(JsonSchemaValidator.matchesJsonSchemaInClasspath("schemas/product-schema.json"));
    }
}
