package com.api.tests;

import com.api.config.ApiConfig;
import com.api.models.Post;
import com.api.base.TestBase;
import com.api.utils.TestDataFactory;
import io.qameta.allure.*;
import io.restassured.response.Response;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;

import java.util.HashMap;
import java.util.Map;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;
import static org.junit.jupiter.api.Assertions.*;

@Epic("API Test Automation")
@Feature("POST Requests")
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class PostRequestTests extends TestBase {

    @Test @Order(1)
    @DisplayName("POST /posts — valid payload should return 201 Created")
    @Story("Create Post") @Severity(SeverityLevel.BLOCKER)
    @Description("POST /posts with a valid JSON body must return HTTP 201 and the created resource")
    void testCreatePost_WithValidPayload_ShouldReturn201() {
        Post newPost = TestDataFactory.createValidPost();

        given()
                .spec(requestSpec)
                .body(newPost)
                .when()
                .post(ApiConfig.POSTS_ENDPOINT)
                .then()
                .statusCode(ApiConfig.STATUS_CREATED)
                .body("id",     notNullValue())
                .body("userId", equalTo(newPost.getUserId()))
                .body("title",  equalTo(newPost.getTitle()))
                .body("body",   equalTo(newPost.getBody()));
    }

    @Test @Order(2)
    @DisplayName("POST /posts — created post should have an auto-generated ID")
    @Story("Create Post") @Severity(SeverityLevel.CRITICAL)
    void testCreatePost_ShouldReturnAutoGeneratedId() {
        Response response = given()
                .spec(requestSpec)
                .body(TestDataFactory.createValidPost())
                .when()
                .post(ApiConfig.POSTS_ENDPOINT)
                .then()
                .statusCode(ApiConfig.STATUS_CREATED)
                .extract().response();

        Integer generatedId = response.jsonPath().getInt("id");
        assertNotNull(generatedId, "Generated ID must not be null");
        assertTrue(generatedId > 0, "Generated ID must be a positive integer");
        log.info("Created post with ID: {}", generatedId);
    }

    @Test @Order(3)
    @DisplayName("POST /posts — raw map payload should return 201")
    @Story("Create Post - Raw Map") @Severity(SeverityLevel.NORMAL)
    void testCreatePost_WithRawMapPayload_ShouldReturn201() {
        Map<String, Object> postPayload = TestDataFactory.createRawPostMap();

        given()
                .spec(requestSpec)
                .body(postPayload)
                .when()
                .post(ApiConfig.POSTS_ENDPOINT)
                .then()
                .statusCode(ApiConfig.STATUS_CREATED)
                .body("title", equalTo(postPayload.get("title")))
                .body("body",  equalTo(postPayload.get("body")));
    }

    @Test @Order(4)
    @DisplayName("POST /posts — response Content-Type should be JSON")
    @Story("POST Response Headers") @Severity(SeverityLevel.MINOR)
    void testCreatePost_ResponseContentTypeShouldBeJson() {
        given()
                .spec(requestSpec)
                .body(TestDataFactory.createValidPost())
                .when()
                .post(ApiConfig.POSTS_ENDPOINT)
                .then()
                .statusCode(ApiConfig.STATUS_CREATED)
                .header(ApiConfig.CONTENT_TYPE_HEADER, containsString("application/json"));
    }

    @Test @Order(5)
    @DisplayName("POST /posts — minimal fields payload should return 201")
    @Story("Create Post - Minimal Payload") @Severity(SeverityLevel.NORMAL)
    void testCreatePost_WithMinimalFields_ShouldReturn201() {
        Map<String, Object> minimalPost = new HashMap<>();
        minimalPost.put("title", "Minimal Post Title");

        given()
                .spec(requestSpec)
                .body(minimalPost)
                .when()
                .post(ApiConfig.POSTS_ENDPOINT)
                .then()
                .statusCode(ApiConfig.STATUS_CREATED)
                .body("id", notNullValue());
    }

    @Test @Order(6)
    @DisplayName("POST /posts — response body should fully match the request")
    @Story("Create Post - Response Body") @Severity(SeverityLevel.CRITICAL)
    void testCreatePost_ResponseBodyShouldMatchRequest() {
        String expectedTitle  = "Divine Test Title " + System.currentTimeMillis();
        String expectedBody   = "Divine test body content for API automation.";
        int    expectedUserId = 7;

        Map<String, Object> payload = new HashMap<>();
        payload.put("userId", expectedUserId);
        payload.put("title",  expectedTitle);
        payload.put("body",   expectedBody);

        Response response = given()
                .spec(requestSpec)
                .body(payload)
                .when()
                .post(ApiConfig.POSTS_ENDPOINT)
                .then()
                .statusCode(ApiConfig.STATUS_CREATED)
                .extract().response();

        assertAll("response body fields",
                () -> assertEquals(expectedUserId, response.jsonPath().getInt("userId"), "userId mismatch"),
                () -> assertEquals(expectedTitle,  response.jsonPath().getString("title"),  "title mismatch"),
                () -> assertEquals(expectedBody,   response.jsonPath().getString("body"),   "body mismatch")
        );
    }

    @Test @Order(7)
    @DisplayName("POST /posts — empty body should be handled gracefully")
    @Story("Create Post - Negative") @Severity(SeverityLevel.NORMAL)
    void testCreatePost_WithEmptyBody_ShouldHandleGracefully() {
        Response response = given()
                .spec(requestSpec)
                .body("{}")
                .when()
                .post(ApiConfig.POSTS_ENDPOINT)
                .then()
                .extract().response();

        int statusCode = response.getStatusCode();
        log.info("Empty body POST returned status: {}", statusCode);
        assertTrue(
                statusCode == ApiConfig.STATUS_CREATED ||
                        statusCode == ApiConfig.STATUS_BAD_REQUEST ||
                        statusCode == ApiConfig.STATUS_UNPROCESSABLE,
                "Unexpected status code for empty body POST: " + statusCode
        );
    }
}
