package com.api.tests.posts;

import com.api.config.ApiConfig;
import com.api.models.Post;
import com.api.base.TestBase;
import com.api.utils.TestDataFactory;
import io.qameta.allure.*;
import io.restassured.response.Response;
import org.junit.jupiter.api.*;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;
import static org.junit.jupiter.api.Assertions.*;

@Epic("API Test Automation")
@Feature("Post Management")
@Story("CREATE Posts")
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
@DisplayName("POST Create API Tests")
public class CreatePostTests extends TestBase {

    @Test
    @Order(1)
    @AllureId("P-001")
    @DisplayName("POST /posts — valid payload should return 201 Created")
    @Severity(SeverityLevel.BLOCKER)
    @Description("API: POST /posts. Validates that a valid payload returns HTTP 201 and the created resource. Issue: Endpoint may fail to create post or return incorrect data.")
    void testCreatePost_WithValidPayload_ShouldReturn201() {
        Post newPost = TestDataFactory.createValidPost();

        given()
                .spec(requestSpec)
                .body(newPost)
                .when()
                .post(ApiConfig.POSTS_ENDPOINT)
                .then()
                .statusCode(ApiConfig.STATUS_OK)
                .body("id", notNullValue())
                .body("userId", equalTo(newPost.getUserId()))
                .body("title", equalTo(newPost.getTitle()))
                .body("body", equalTo(newPost.getBody()));
    }

    @Test
    @Order(2)
    @AllureId("P-002")
    @DisplayName("POST /posts — created post should have an auto-generated ID")
    @Severity(SeverityLevel.CRITICAL)
    @Description("API: POST /posts. Checks that the created post has an auto-generated ID. Issue: ID may not be generated or is null.")
    void testCreatePost_ShouldReturnAutoGeneratedId() {
        Response response = given()
                .spec(requestSpec)
                .body(TestDataFactory.createValidPost())
                .when()
                .post(ApiConfig.POSTS_ENDPOINT)
                .then()
                .statusCode(ApiConfig.STATUS_CREATED)
                .extract().response();

        Integer generatedId = response.jsonPath().get("id");
        assertNotNull(generatedId, "Generated ID must not be null");
        log.info("Created post with ID: {}", generatedId);
    }

    @Test
    @Order(3)
    @AllureId("P-003")
    @DisplayName("POST /posts — response body should fully match the request")
    @Severity(SeverityLevel.CRITICAL)
    @Description("API: POST /posts. Ensures the response body matches the request payload. Issue: Response data may not match sent data.")
    void testCreatePost_ResponseBodyShouldMatchRequest() {
        String expectedTitle = "Test Title " + System.currentTimeMillis();
        String expectedBody = "Test body content.";
        int expectedUserId = 1;

        java.util.Map<String, Object> payload = new java.util.HashMap<>();
        payload.put("userId", expectedUserId);
        payload.put("title", expectedTitle);
        payload.put("body", expectedBody);

        given()
                .spec(requestSpec)
                .body(payload)
                .when()
                .post(ApiConfig.POSTS_ENDPOINT)
                .then()
                .statusCode(ApiConfig.STATUS_CREATED)
                .body("userId", equalTo(expectedUserId))
                .body("title", equalTo(expectedTitle))
                .body("body", equalTo(expectedBody));
    }
}
