package com.api.tests.posts;

import com.api.config.ApiConfig;
import com.api.base.TestBase;
import io.qameta.allure.*;
import io.restassured.response.Response;
import org.junit.jupiter.api.*;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;

import java.util.Map;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;
import static org.junit.jupiter.api.Assertions.*;

@Epic("API Test Automation")
@Feature("Post Management")
@Story("CREATE Posts")
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
@DisplayName("POST Create API Tests")
public class CreatePostTests extends TestBase {

    @ParameterizedTest(name = "POST /posts — valid payload {0}")
    @Order(1)
    @AllureId("P-001")
    @MethodSource("com.api.tests.posts.PostDataFactory#validPostProvider")
    @Severity(SeverityLevel.BLOCKER)
    @Description("API: POST /posts. Validates that various valid payloads return HTTP 201 Created.")
    void testCreatePost_WithValidPayload_ShouldReturn201(Map<String, Object> payload) {
        given()
                .spec(requestSpec)
                .body(payload)
                .when()
                .post(ApiConfig.POSTS_ENDPOINT)
                .then()
                .statusCode(ApiConfig.STATUS_CREATED)
                .body("id", notNullValue())
                .body("userId", equalTo(payload.get("userId")))
                .body("title", equalTo(payload.get("title")))
                .body("body", equalTo(payload.get("body")));
    }

    @Test
    @Order(2)
    @AllureId("P-002")
    @DisplayName("POST /posts — created post should have an auto-generated ID")
    @Severity(SeverityLevel.CRITICAL)
    @Description("API: POST /posts. Checks that the created post has an auto-generated ID. Issue: ID may not be generated or is null.")
    void testCreatePost_ShouldReturnAutoGeneratedId() {
        Response response = given()
                .spec(requestSpec)
                .body(PostDataFactory.createValidPost())
                .when()
                .post(ApiConfig.POSTS_ENDPOINT)
                .then()
                .statusCode(ApiConfig.STATUS_CREATED)
                .extract().response();

        Integer generatedId = response.jsonPath().get("id");
        assertNotNull(generatedId, "Generated ID must not be null");
        log.info("Created post with ID: {}", generatedId);
    }

    @Test
    @Order(3)
    @AllureId("P-003")
    @DisplayName("POST /posts — response body should fully match the request")
    @Severity(SeverityLevel.CRITICAL)
    @Description("API: POST /posts. Ensures the response body matches the request payload. Issue: Response data may not match sent data.")
    void testCreatePost_ResponseBodyShouldMatchRequest() {
        String expectedTitle = "Test Title " + System.currentTimeMillis();
        String expectedBody = "Test body content.";
        int expectedUserId = 1;

        java.util.Map<String, Object> payload = new java.util.HashMap<>();
        payload.put("userId", expectedUserId);
        payload.put("title", expectedTitle);
        payload.put("body", expectedBody);

        given()
                .spec(requestSpec)
                .body(payload)
                .when()
                .post(ApiConfig.POSTS_ENDPOINT)
                .then()
                .statusCode(ApiConfig.STATUS_CREATED)
                .body("userId", equalTo(expectedUserId))
                .body("title", equalTo(expectedTitle))
                .body("body", equalTo(expectedBody));
    }
}
